<{{ !empty($opts->tag) ? $opts->tag : 'div' }}{!! !empty($opts->classes) ? ' class="' . implode(" ", $opts->classes) . '"' : '' !!}{!! !empty($opts->src) ? ' src="' . $opts->src . '"' : '' !!}{!! !empty($opts->onClick) ? ' @click="' . $opts->onClick . '()"' : '' !!}{!! !empty($opts->onDblClick) ? ' @dblClick="' . $opts->onDblClick . '()"' : '' !!}{!! !empty($opts->onChange) ? ' @change="' . $opts->onChange . '()"' : '' !!}{!! !empty($opts->onInput) ? ' @input="' . $opts->onInput . '()"' : '' !!}{!! !empty($opts->onFocus) ? ' @focus="' . $opts->onFocus . '()"' : '' !!}{!! !empty($opts->onBlur) ? ' @blur="' . $opts->onBlur . '()"' : '' !!}{!! !empty($opts->onKeyUp) ? ' @keyup="' . $opts->onKeyUp . '()"' : '' !!}{!! !empty($opts->onKeyDown) ? ' @keydown="' . $opts->onKeyDown . '()"' : '' !!}{!! !empty($opts->onMouseEnter) ? ' @mouseenter="' . $opts->onMouseEnter . '()"' : '' !!}{!! !empty($opts->onMouseLeave) ? ' @mouseleave="' . $opts->onMouseLeave . '()"' : '' !!}{!! !empty($opts->onDrag) ? ' @drag="' . $opts->onDrag . '()"' : '' !!}{!! !empty($opts->onRelease) ? ' @release="' . $opts->onRelease . '()"' : '' !!}{!! !empty($opts->href) ? ' href="' . $opts->href . '"' : '' !!}{!! !empty($opts->target) ? ' target="' . $opts->target . '"' : '' !!}{!! !empty($opts->name) ? ' name="' . $opts->name . '"' : '' !!}{!! !empty($opts->inputType) ? ' type="' . $opts->inputType . '"' : '' !!}{!! !empty($opts->width) ? ' width="' . $opts->width . '"' : '' !!}{!! !empty($opts->height) ? ' height="' . $opts->height . '"' : '' !!}{!! !empty($opts->title) ? ' title="' . $opts->title . '"' : '' !!}{!! !empty($opts->download) ? ' download="' . $opts->download . '"' : '' !!}{!! !empty($opts->rel) ? ' rel="' . $opts->rel . '"' : '' !!}{!! !empty($opts->id) ? ' id="' . $opts->id . '"' : '' !!}{!! !empty($opts->ref) ? ' ref="' . $opts->ref . '"' : '' !!}{!! !empty($opts->arialabel) ? ' arialabel="' . $opts->arialabel . '"' : '' !!}{!! !empty($opts->role) ? ' role="' . $opts->role . '"' : '' !!}{!! !empty($opts->action) ? ' action="' . $opts->action . '"' : '' !!}{!! !empty($opts->method) ? ' method="' . $opts->method . '"' : '' !!}{!! !empty($opts->enctype) ? ' enctype="' . $opts->enctype . '"' : '' !!}{!! !empty($opts->viewBox) ? ' viewBox="' . $opts->viewBox . '"' : '' !!}{!! !empty($opts->fill) ? ' fill="' . $opts->fill . '"' : '' !!}{!! !empty($opts->stroke) ? ' stroke="' . $opts->stroke . '"' : '' !!}{!! !empty($opts->{'stroke-width'}) ? ' stroke-width="' . $opts->{'stroke-width'} . '"' : '' !!}{!! !empty($opts->{'stroke-linecap'}) ? ' stroke-linecap="' . $opts->{'stroke-linecap'} . '"' : '' !!}{!! !empty($opts->{'d'}) ? ' d="' . $opts->{'d'} . '"' : '' !!}{!! !empty($opts->tag) && $opts->tag == 'svg' ? ' xmlns=http://www.w3.org/2000/svg' : false !!}{!! !empty($opts->tag) && $opts->tag == 'svg' ? ' xmlns:xlink=http://www.w3.org/1999/xlink' : false !!}>{{ !empty($opts->text) ? $opts->text : '' }}
    @if (!empty($opts->data))
        @foreach($opts->data as $key => $data)
            <x-dynamic-component 
                component="wrapper"  
                :opts="$content[$data]" 
                :settings="$settings" 
                :content="$content"
            />
        @endforeach
    @endif
</{{ !empty($opts->tag) ? $opts->tag : 'div' }}>
