import { defineStore } from 'pinia';

export const ProductionStore = defineStore('stellifyStore', {
    state : () => (
        {
            content: window.App.content ? window.App.content : {},
            page: window.App.body,
            route: window.App.route,
            project: window.App.project,
            errors: window.App.errors,
            settings: window.App.settings,
            variables: window.App.variables,
            files: window.App.files ? window.App.files : {},
            methods: window.App.methods,
            statements: window.App.statements,
            clauses: window.App.clauses,
            user: window.App.user,
            jsTokens: {
				var: 'var ',
				let: 'let ',
				const: 'const ',
				function: 'function ',
				if: 'if ',
				else: 'else ',
				for: 'for ',
				while: 'while ',
				do: 'do ',
				switch: 'switch ',
				case: 'case ',
				default: 'default ',
				return: 'return ',
                arrow: ' => ',
				break: 'break',
				continue: 'continue',
				throw: 'throw ',
				try: 'try',
				catch: 'catch ',
				finally: 'finally',
				class: 'class ',
				extends: 'extends ',
				super: 'super',
				import: 'import ',
				export: 'export ',
				new: 'new ',
				this: 'this',
				in: 'in ',
				instanceof: 'instanceof ',
				typeof: 'typeof ',
				void: 'void ',
				delete: 'delete ',
				async: 'async ',
				await: 'await ',
				yield: 'yield ',
				with: 'with ',
				null: 'null',
				undefined: '',
				nan: 'NaN',
				infinity: 'Infinity',
				addition: ' + ',
				subtraction: ' - ',
				multiplication: ' * ',
				division: ' / ',
				modulus: '%',
				increment: '++',
				decrement: '--',
				assignment: ' = ',
				addition_assignment: ' += ',
				subtraction_assignment: ' -= ',
				multiplication_assignment: ' *= ',
				division_assignment: ' /= ',
				modulus_assignment: ' %= ',
				equal: ' == ',
				strict_equal: ' === ',
				not_equal: ' != ',
				strict_not_equal: ' !== ',
				greater_than: ' > ',
				greater_than_or_equal: ' >= ',
				less_than: ' < ',
				less_than_or_equal: ' <= ',
				logical_and: ' && ',
				logical_or: ' || ',
				logical_not: '!',
				bitwise_and: ' & ',
				bitwise_or: ' | ',
				bitwise_not: ' ~ ',
				bitwise_xor: ' ^ ',
				left_shift: '<<',
				right_shift: '>>',
				unsigned_right_shift: '>>>',
				ternary: ' ? ',
				open_parenthesis: '(',
				close_parenthesis: ')',
				open_bracket: '[',
				close_bracket: ']',
				open_brace: '{',
				close_brace: '}',
				semicolon: ';',
				colon: ':',
				comma: ',',
				period: '.',
				start: '`',
				end: '`',
				placeholder_start: '${',
				placeholder_end: '}'
			}
		}
    )
})